#!/usr/bin/env python3
"""
setup.py — Interactive CLI setup for readme-world.

Usage:
    python setup.py

What it does:
    1. Prompts for city name (and optionally a user display name, biome,
       character, and weather mode).
    2. Calls the Open-Meteo Geocoding API (free, no key) to resolve
       latitude / longitude from the city name.
    3. Uses timezonefinder to derive the IANA timezone string.
    4. Writes every value into world.config.yml.
"""

import sys
import os
import requests
import yaml
from timezonefinder import TimezoneFinder

CONFIG_PATH = os.path.join(os.path.dirname(__file__), "world.config.yml")
GEOCODE_API = "https://geocoding-api.open-meteo.com/v1/search"

BIOMES = ["forest", "desert", "snow", "beach"]
CHARACTERS = ["cat"]
WEATHER_MODES = ["real", "static"]

# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def ask(prompt: str, default: str = "", choices: list = None) -> str:
    """Prompt the user for input with an optional default and choice list."""
    choice_hint = ""
    if choices:
        choice_hint = f" [{'/'.join(choices)}]"
    default_hint = f" (default: {default})" if default else ""
    full_prompt = f"{prompt}{choice_hint}{default_hint}: "

    while True:
        value = input(full_prompt).strip()
        if not value:
            if default:
                return default
            else:
                print("  ✗ This field is required.")
                continue
        if choices and value not in choices:
            print(f"  ✗ Please choose one of: {', '.join(choices)}")
            continue
        return value


def geocode_city(city: str) -> dict:
    """
    Call the Open-Meteo geocoding API and return the best match as a dict
    with keys: name, latitude, longitude, country, admin1.
    Raises RuntimeError if no results are found.
    """
    print(f"\n  🌐 Looking up '{city}' via Open-Meteo Geocoding API …")
    try:
        resp = requests.get(
            GEOCODE_API,
            params={"name": city, "count": 5, "language": "en", "format": "json"},
            timeout=10,
        )
        resp.raise_for_status()
    except requests.RequestException as exc:
        raise RuntimeError(f"Network error while geocoding: {exc}") from exc

    data = resp.json()
    results = data.get("results")
    if not results:
        raise RuntimeError(
            f"No locations found for '{city}'. "
            "Try a different spelling or a nearby larger city."
        )

    # Show top matches so the user can pick
    print(f"\n  Found {len(results)} result(s):\n")
    for i, r in enumerate(results):
        admin = r.get("admin1", "")
        country = r.get("country", "")
        region = f"{admin}, {country}".strip(", ")
        print(f"  [{i + 1}] {r['name']}  —  {region}  "
              f"(lat: {r['latitude']:.4f}, lon: {r['longitude']:.4f})")

    print()
    if len(results) == 1:
        choice_idx = 1
    else:
        while True:
            raw = input(f"  Select location [1-{len(results)}] (default: 1): ").strip()
            if not raw:
                choice_idx = 1
                break
            if raw.isdigit() and 1 <= int(raw) <= len(results):
                choice_idx = int(raw)
                break
            print(f"  ✗ Please enter a number between 1 and {len(results)}.")

    return results[choice_idx - 1]


def derive_timezone(lat: float, lon: float) -> str:
    """Return the IANA timezone string for the given coordinates."""
    tf = TimezoneFinder()
    tz = tf.timezone_at(lat=lat, lng=lon)
    if not tz:
        # Fallback: rough UTC offset estimation is not needed because
        # timezonefinder covers the entire globe. If it genuinely returns
        # None (e.g., open ocean), fall back to UTC.
        tz = "UTC"
    return tz


def load_existing_config() -> dict:
    """Load the existing config file if present, otherwise return defaults."""
    defaults = {
        "character": "cat",
        "biome": "forest",
        "name": "",
        "weather": "real",
        "latitude": 0.0,
        "longitude": 0.0,
        "timezone": "UTC",
        "weather_update_hours": 3,
    }
    if os.path.exists(CONFIG_PATH):
        with open(CONFIG_PATH, "r", encoding="utf-8") as fh:
            loaded = yaml.safe_load(fh) or {}
        defaults.update(loaded)
    return defaults


def write_config(cfg: dict) -> None:
    """Write the config dict to world.config.yml with human-friendly comments."""
    lines = [
        "# readme-world configuration",
        "# Generated by setup.py — you can edit this file manually too.",
        "",
        f"character: {cfg['character']}          "
        "# Pixel-art character (currently only \"cat\" is supported)",
        f"biome: {cfg['biome']}           "
        "# World biome: forest | desert | snow | beach",
        f"name: {cfg['name']}            "
        "# Your name — shown in the SVG greeting",
        "",
        f"weather: {cfg['weather']}           "
        "# \"real\" = fetch from Open-Meteo | \"static\" = always clear",
        "",
        "# Geographic coordinates (used for timezone + sunrise/sunset)",
        f"latitude: {cfg['latitude']}",
        f"longitude: {cfg['longitude']}",
        f"timezone: {cfg['timezone']}  "
        "# IANA timezone string",
        "",
        "# How many hours between live weather API refreshes.",
        "# Between refreshes the last cached state.json value is used.",
        f"weather_update_hours: {cfg['weather_update_hours']}",
    ]
    with open(CONFIG_PATH, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main() -> None:
    print("╔══════════════════════════════════════════════════╗")
    print("║   readme-world — Interactive Setup               ║")
    print("╚══════════════════════════════════════════════════╝")
    print()

    existing = load_existing_config()

    # ── Display name ──────────────────────────────────────────────────────────
    name = ask(
        "Your display name (shown in the SVG)",
        default=existing.get("name") or "Traveller",
    )

    # ── City lookup ───────────────────────────────────────────────────────────
    city_input = ask("Your city name (for weather & timezone lookup)")

    try:
        location = geocode_city(city_input)
    except RuntimeError as exc:
        print(f"\n  ✗ {exc}")
        sys.exit(1)

    lat = location["latitude"]
    lon = location["longitude"]
    city_name = location["name"]

    print(f"\n  ✔ Using: {city_name}  (lat={lat}, lon={lon})")

    # ── Timezone ──────────────────────────────────────────────────────────────
    print("  🕐 Detecting timezone …")
    tz = derive_timezone(lat, lon)
    print(f"  ✔ Timezone: {tz}")

    # ── Biome ─────────────────────────────────────────────────────────────────
    biome = ask(
        "Choose a biome",
        default=existing.get("biome", "forest"),
        choices=BIOMES,
    )

    # ── Character ─────────────────────────────────────────────────────────────
    character = ask(
        "Choose a character",
        default=existing.get("character", "cat"),
        choices=CHARACTERS,
    )

    # ── Weather mode ──────────────────────────────────────────────────────────
    weather = ask(
        "Weather mode",
        default=existing.get("weather", "real"),
        choices=WEATHER_MODES,
    )

    # ── Weather update interval ───────────────────────────────────────────────
    while True:
        raw_hours = input(
            f"  Weather refresh interval in hours (default: "
            f"{existing.get('weather_update_hours', 3)}): "
        ).strip()
        if not raw_hours:
            weather_update_hours = existing.get("weather_update_hours", 3)
            break
        if raw_hours.isdigit() and int(raw_hours) > 0:
            weather_update_hours = int(raw_hours)
            break
        print("  ✗ Please enter a positive integer.")

    # ── Assemble & write ──────────────────────────────────────────────────────
    cfg = {
        "character": character,
        "biome": biome,
        "name": name,
        "weather": weather,
        "latitude": round(lat, 6),
        "longitude": round(lon, 6),
        "timezone": tz,
        "weather_update_hours": weather_update_hours,
    }

    write_config(cfg)

    print()
    print("  ✔ world.config.yml written successfully!")
    print()
    print("  Next steps:")
    print("  1. Commit world.config.yml to your repo.")
    print("  2. The GitHub Actions workflow will run generate_world.py")
    print("     every 30 minutes and update world.svg on the output branch.")
    print("  3. Add this to your profile README:")
    print()
    print("     ![readme-world]"
          "(https://raw.githubusercontent.com/<user>/<repo>/output/world.svg)")
    print()


if __name__ == "__main__":
    main()
