#!/usr/bin/env python3
"""
setup.py — Interactive CLI setup for readme-world.

Usage:
    python setup.py

What it does:
    1. Prompts for display name, character, and biome.
    2. Writes every value into world.config.yml.
"""

import sys
import os
import yaml

CONFIG_PATH = os.path.join(os.path.dirname(__file__), "world.config.yml")

BIOMES = ["forest"]
CHARACTERS = ["cat", "dog"]

def ask(prompt: str, default: str = "", choices: list = None) -> str:
    choice_hint = ""
    if choices:
        choice_hint = f" [{'/'.join(choices)}]"
    default_hint = f" (default: {default})" if default else ""
    full_prompt = f"{prompt}{choice_hint}{default_hint}: "

    while True:
        value = input(full_prompt).strip()
        if not value:
            if default:
                return default
            else:
                print("  ✗ This field is required.")
                continue
        if choices and value not in choices:
            print(f"  ✗ Please choose one of: {', '.join(choices)}")
            continue
        return value

def load_existing_config() -> dict:
    defaults = {
        "name": "",
        "character": "cat",
        "biome": "forest",
    }
    if os.path.exists(CONFIG_PATH):
        with open(CONFIG_PATH, "r", encoding="utf-8") as fh:
            loaded = yaml.safe_load(fh) or {}
        defaults.update(loaded)
    return defaults

def write_config(cfg: dict) -> None:
    lines = [
        "# readme-world configuration",
        "# Generated by setup.py — you can edit this file manually too.",
        "",
        f"name: {cfg['name']}",
        f"character: {cfg['character']}",
        f"biome: {cfg['biome']}",
    ]
    with open(CONFIG_PATH, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

def main() -> None:
    print("╔══════════════════════════════════════════════════╗")
    print("║   readme-world — Interactive Setup               ║")
    print("╚══════════════════════════════════════════════════╝")
    print()

    existing = load_existing_config()

    name = ask("Your display name", default=existing.get("name") or "Traveller")
    character = ask("Choose a character", default=existing.get("character", "cat"), choices=CHARACTERS)
    biome = ask("Choose a biome", default=existing.get("biome", "forest"), choices=BIOMES)

    cfg = {
        "name": name,
        "character": character,
        "biome": biome,
    }

    write_config(cfg)

    print("\n  ✔ world.config.yml written successfully!\n")

if __name__ == "__main__":
    main()
